<?php declare(strict_types=1); 

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();
        
        $products = [
            [
                'name' => 'CARTOUCHE HP 37A',
                'description' => "Cartouche HP 37A pour impressions nettes et durables sur imprimantes compatibles.",
                'short_description' => "Cartouche HP 37A noire.",
                'mode_emploi' => "Ouvrez le capot de l'imprimante, retirez l'ancienne cartouche et insérez la nouvelle jusqu'au clic.",
                'caracteristiques' => "Compatibilité : HP, Couleur : Noir.",
                'price' => 50000,
                'stock_quantity' => 10,
                'sku' => 'ART0003',
                'is_active' => true,
                'is_featured' => false,
                'category_id' => $categories->where('name', "Cartouches d’encre & Toners")->first()?->id,
                'meta_title' => "Cartouche HP 37A - ADI Store",
                'meta_description' => "Cartouche HP 37A pour impressions de qualité.",
                'meta_keywords' => "cartouche, HP, 37A, encre",
            ],
            [
                'name' => 'CARTOUCHE HP 87A',
                'description' => "Cartouche HP 87A pour des impressions professionnelles et durables.",
                'short_description' => "Cartouche HP 87A noire.",
                'mode_emploi' => "Ouvrez le capot de l'imprimante, retirez l'ancienne cartouche et insérez la nouvelle jusqu'au clic.",
                'caracteristiques' => "Compatibilité : HP, Couleur : Noir.",
                'price' => 70000,
                'stock_quantity' => 10,
                'sku' => 'ART0002',
                'is_active' => true,
                'is_featured' => false,
                'category_id' => $categories->where('name', "Cartouches d’encre & Toners")->first()?->id,
                'meta_title' => "Cartouche HP 87A - ADI Store",
                'meta_description' => "Cartouche HP 87A pour impressions de qualité.",
                'meta_keywords' => "cartouche, HP, 87A, encre",
            ],
            [
                'name' => 'IMPRIMANTE HP 4303 FDW',
                'description' => "Imprimante multifonction HP 4303 FDW, idéale pour les bureaux exigeant rapidité et fiabilité.",
                'short_description' => "Imprimante multifonction laser, impression rapide.",
                'mode_emploi' => "Branchez l'imprimante, installez les cartouches, connectez au réseau et lancez l'installation via le logiciel HP.",
                'caracteristiques' => "Technologie : Laser, Fonctions : Impression, scan, copie, fax, Connectivité : USB, Wi-Fi, Ethernet.",
                'price' => 470000,
                'stock_quantity' => 10,
                'sku' => 'ART4505',
                'is_active' => true,
                'is_featured' => true,
                'category_id' => $categories->where('name', 'Imprimantes')->first()?->id,
                'meta_title' => "Imprimante HP 4303 FDW - ADI Store",
                'meta_description' => "Imprimante multifonction HP 4303 FDW pour professionnels.",
                'meta_keywords' => "imprimante, HP, 4303, laser, multifonction",
            ],
            [
                'name' => 'ECRAN LED 27 POUCES 5275F',
                'description' => "Écran LED 27 pouces, résolution Full HD, parfait pour le travail et le divertissement.",
                'short_description' => "Écran LED 27 Full HD.",
                'mode_emploi' => "Connectez l'écran à votre ordinateur via HDMI ou VGA, ajustez la luminosité selon vos besoins.",
                'caracteristiques' => "Taille : 27 pouces, Résolution : 1920x1080, Connectique : HDMI, VGA.",
                'price' => 160000,
                'stock_quantity' => 10,
                'sku' => 'ART0504',
                'is_active' => true,
                'is_featured' => true,
                'category_id' => $categories->where('name', 'Écrans')->first()?->id,
                'meta_title' => "Écran LED 27 pouces - ADI Store",
                'meta_description' => "Écran LED 27 pouces Full HD pour une expérience visuelle optimale.",
                'meta_keywords' => "écran, LED, 27 pouces, Full HD",
            ],
            [
                'name' => 'ORDINATEUR HP 290 I5 RAM 4GO DISQUE DUR 1TERA AVEC ECRAN 24 POUCE',
                'description' => "Ordinateur HP 290 avec processeur Intel Core i5, 4Go RAM, disque dur 1To et écran 24 pouces inclus.",
                'short_description' => "PC HP 290 i5, 4Go RAM, 1To HDD, écran 24.",
                'mode_emploi' => "Branchez l'ordinateur, connectez les périphériques, démarrez et suivez l'assistant de configuration Windows.",
                'caracteristiques' => "Processeur : Intel Core i5, RAM : 4Go, Stockage : 1To, Écran : 24 pouces.",
                'price' => 400000,
                'stock_quantity' => 10,
                'sku' => 'ART0569',
                'is_active' => true,
                'is_featured' => true,
                'category_id' => $categories->where('name', 'Ordinateurs')->first()?->id,
                'meta_title' => "Ordinateur HP 290 i5 - ADI Store",
                'meta_description' => "Ordinateur HP 290 i5 avec écran 24 pouces.",
                'meta_keywords' => "ordinateur, HP, 290, i5, 24 pouces",
            ],
            [
                'name' => 'CLES USB 32GO',
                'description' => "Clé USB 32Go, idéale pour le stockage et le transfert de fichiers.",
                'short_description' => "Clé USB 32Go.",
                'mode_emploi' => "Insérez la clé dans un port USB, attendez la détection automatique, copiez vos fichiers.",
                'caracteristiques' => "Capacité : 32Go, Interface : USB 3.0.",
                'price' => 5000,
                'stock_quantity' => 10,
                'sku' => 'ART0144',
                'is_active' => true,
                'is_featured' => false,
                'category_id' => $categories->where('name', 'Accessoires')->first()?->id,
                'meta_title' => "Clé USB 32Go - ADI Store",
                'meta_description' => "Clé USB 32Go rapide et fiable.",
                'meta_keywords' => "clé USB, 32Go, stockage",
            ],
            [
                'name' => 'SCANJET PRO 3000 S3',
                'description' => "Scanner professionnel HP ScanJet Pro 3000 S3, rapide et précis.",
                'short_description' => "Scanner HP ScanJet Pro 3000 S3.",
                'mode_emploi' => "Branchez le scanner, installez le pilote, placez le document et lancez la numérisation.",
                'caracteristiques' => "Type : Scanner à plat, Vitesse : 35 ppm, Résolution : 600 dpi.",
                'price' => 390000,
                'stock_quantity' => 10,
                'sku' => 'ART0097',
                'is_active' => true,
                'is_featured' => false,
                'category_id' => $categories->where('name', 'Scanners')->first()?->id,
                'meta_title' => "Scanner HP ScanJet Pro 3000 S3 - ADI Store",
                'meta_description' => "Scanner professionnel HP ScanJet Pro 3000 S3.",
                'meta_keywords' => "scanner, HP, ScanJet, 3000 S3",
            ],
            [
                'name' => 'PHOTOCOPIEUSE CANON IRC 3226I COMPLET',
                'description' => "Photocopieuse Canon IRC 3226i multifonction, idéale pour les entreprises.",
                'short_description' => "Photocopieuse Canon IRC 3226i.",
                'mode_emploi' => "Branchez la photocopieuse, chargez le papier, configurez via le panneau de contrôle.",
                'caracteristiques' => "Fonctions : Copie, impression, scan, fax, Connectivité : USB, réseau.",
                'price' => 1950000,
                'stock_quantity' => 10,
                'sku' => 'ART0542',
                'is_active' => true,
                'is_featured' => true,
                'category_id' => $categories->where('name', 'Photocopieurs')->first()?->id,
                'meta_title' => "Photocopieuse Canon IRC 3226i - ADI Store",
                'meta_description' => "Photocopieuse Canon IRC 3226i multifonction.",
                'meta_keywords' => "photocopieuse, Canon, IRC 3226i, multifonction",
            ],
            [
                'name' => 'CARTOUCHE HP 953 NOIR',
                'description' => "Cartouche d'encre HP 953 noire, pour des impressions nettes et durables.",
                'short_description' => "Cartouche HP 953 noire.",
                'mode_emploi' => "Ouvrez le capot de l'imprimante, retirez l'ancienne cartouche et insérez la nouvelle jusqu'au clic.",
                'caracteristiques' => "Compatibilité : HP OfficeJet Pro, Couleur : Noir.",
                'price' => 22000,
                'stock_quantity' => 10,
                'sku' => 'ART0053',
                'is_active' => true,
                'is_featured' => false,
                'category_id' => $categories->where('name', "Cartouches d’encre & Toners")->first()?->id,
                'meta_title' => "Cartouche HP 953 Noir - ADI Store",
                'meta_description' => "Cartouche d'encre HP 953 noire pour impressions de qualité.",
                'meta_keywords' => "cartouche, HP, 953, noir, encre",
            ],
            [
                'name' => 'CARTOUCHE CANON 054 NOIR BLEU JAUNE ROUGE',
                'description' => "Cartouche Canon 054 pour impressions couleur de haute qualité.",
                'short_description' => "Cartouche Canon 054 (noir, bleu, jaune, rouge).",
                'mode_emploi' => "Ouvrez le capot de l'imprimante, retirez l'ancienne cartouche et insérez la nouvelle jusqu'au clic.",
                'caracteristiques' => "Compatibilité : Canon, Couleurs : Noir, Bleu, Jaune, Rouge.",
                'price' => 50000,
                'stock_quantity' => 10,
                'sku' => 'ART0056',
                'is_active' => true,
                'is_featured' => false,
                'category_id' => $categories->where('name', "Cartouches d’encre & Toners")->first()?->id,
                'meta_title' => "Cartouche Canon 054 - ADI Store",
                'meta_description' => "Cartouche Canon 054 pour impressions couleur.",
                'meta_keywords' => "cartouche, Canon, 054, couleur",
            ],
        ];

        foreach ($products as $product) {
            Product::create([
                'name' => $product['name'],
                'slug' => Str::slug($product['name']),
                'description' => $product['description'],
                'short_description' => $product['short_description'],
                'mode_emploi' => $product['mode_emploi'],
                'caracteristiques' => $product['caracteristiques'],
                'price' => $product['price'],
                'sale_price' => $product['sale_price'] ?? null,
                'stock_quantity' => $product['stock_quantity'],
                'sku' => $product['sku'],
                'is_active' => $product['is_active'],
                'is_featured' => $product['is_featured'] ?? false,
                'is_on_sale' => $product['is_on_sale'] ?? false,
                'category_id' => $product['category_id'],
                'meta_title' => $product['meta_title'],
                'meta_description' => $product['meta_description'],
                'meta_keywords' => $product['meta_keywords'],
                'view_count' => rand(0, 1000),
            ]);
        }
    }
}
